# Generated by Django 2.2.4 on 2019-08-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='users',
            new_name='user',
        ),
    ]
